defaults:
  - _self_
  - go2
  - ppo
  - sim
headless: True
device: "cuda:0"
seed: 0

num_envs: 200
max_episode_length: 2200
sim_dt: 0.005
decimation: 4
max_frame_num: 12e8
eval_interval: 1000
save_interval: 1000

env:
  num_envs: ${num_envs}
  max_episode_length: ${max_episode_length}
  env_spacing: 8.0
  num_obstacles: 80
  map_range: 15.0

env_dyn:
  num_obstacles: 80
  vel_range: [ 0.5, 1.5 ]
  local_range: [ 3.0, 3.0 ]
  
  enable_visualization: true
  max_obs_width: 1.0
  max_obs_height: 2.0

viewer:
  eye: [ 0., 40., 40. ]
  lookat: [ 0., 2.5, 0. ]
  resolution: [ 960, 720 ]

wandb:
  project: go2_navrl
  name: train
  entity: null
  mode: online
  run_id: null               
